name: UI Testing

on:
  schedule:
    - cron: '0 9 * * *'
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]
env:
  app_name: FrontendTesting
  RESULTS_DIRECTORY: ./.github/workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          distribution: 'temurin'
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Install Google Chrome
        run: |
          chmod +x ./scripts/InstallChrome.sh
                      ./scripts/InstallChrome.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: FrontendTesting/build/reports/tests/test

  UI-Testing:
    name: Frontend Automation
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.5
      - name: Run Frontend Tests
        run: |
          ./gradlew clean build -Dsuite=test.xml -i 

      - name:  Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: FrontendTesting/build/reports/tests/test
